spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/neutron_crm
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: db/liquibase/master.xml
  main:
    allow-circular-references: true

logging:
  level:
    net.ttddyy.dsproxy.listener: debug
